### ISSUE TITLE
Room broken, cannot edit item.

### ISSUE THREAD

**Issue by CGsama** [mei23/misskey-v11#1409]
## 💡 Summary

In the my room page, placed item cannot be edit

## 🙂 Expected Behavior

pop up a panel to edit the item

## ☹️ Actual Behavior

the panel not pop up

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

11.37.1-20210626041432
maybe earlier, since not use it for a while

**Comment by CGsama** [comment]
try debug a bit, seems like the click event not linked to the select action

**Comment by mei23** [comment]
Thank you for reporting.
Seems to work with the latest version of `three`.
https://github.com/mei23/misskey-v11/commit/59a56abcc274a24737189b8612717b81026aa7da

However, it seems that there are still problems with move and rotation.

**Comment by mei23** [comment]
Works fine before three r120, but is vulnerable.

I don't know how to change it.
https://github.com/mrdoob/three.js/wiki/Migration-Guide#r119--r120
> OrbitControls, TrackballControls and TransformControls now use Pointer Events. This change might require that you move your custom event listeners to Pointer Events, too.

**Comment by mei23** [comment]
Fixed transform problem
https://github.com/mei23/misskey-v11/commit/b1cef9776ff4c343872f0f5332f9cc181e44268a
