### ISSUE TITLE
Firefox new tab Uncaught TypeError: document.body is null

### ISSUE THREAD

**Issue by CGsama** [mei23/misskey-v11#2318]
## 💡 Summary

Firefox open in note or something in new tab with mid key got error Uncaught TypeError: document.body is null and stuck at loading screen, refresh page will load everything normally

## 🙂 Expected Behavior

load MiOS

## ☹️ Actual Behavior

stuck at loading screen

## 📌 Environment
v11.37.1-20221204012750

Follow fix not working:
the base.pug load js before body,
a dirty fix would be change line 363 in init.ts to "setTimeout(function(){os.init(() => {" and close it without time at line 514

**Comment by mei23** [comment]
This shouldn't happen due to the script defer attribute.
However, Firefox (v108.0) seems to ignore it in some cases.

**Comment by mei23** [comment]
According to the specifications, it seems better not to add async and defer at the same time.
https://github.com/mei23/misskey-v11/pull/2319#issuecomment-1350905165
