### ISSUE TITLE
ナビゲーションバーが左/右の場合に操作できなくなるメニューが存在する

### ISSUE THREAD

**Issue by tkmrgit** [mei23/misskey-v11#2500]
## 💡 Summary

ナビゲーションバーが左/右設定の場合、ページ及びルーム機能がメニューにないため呼び出すことができない

## 🙂 Expected Behavior

ナビゲーションバーが左/右設定の場合でもすべてのメニューが呼び出せる

## ☹️ Actual Behavior

ナビゲーションバーが左/右設定の場合は一部のメニューが呼び出せない

## 📝 Steps to Reproduce

1.Misskeyを開く
2.設定からデザイン→ナビゲーションバーを左・右にする
3.Wow

## 📌 Environment

11.37.1-20231128072711

**Comment by mei23** [comment]
v10だと直したけどいまさらこっち直すのめんどくさいのだわ

**Comment by tkmrgit** [comment]
```
<div class="pages" :class="{ active: $route.name == 'pages' }">
<router-link to="/i/page"><fa :icon="faStickyNote"/></router-link>
</div>
<div class="room" :class="{ active: $route.name == 'room' }">
<router-link :to="`/@${ $store.state.i.username }/room`"><fa :icon="faDoorOpen"/></router-link>
</div>
```
※v10のソースからの見様見真似 https://github.com/mei23/misskey-v11/blob/mei-v11/src/client/app/desktop/views/components/ui.sidebar.vue にこれ追加いけるかしら。これだと動かないか他にもしにゃいといけにゃかったら私には理解不能かも
