### ISSUE TITLE
signToActivityPubGet option seems not working 

### ISSUE THREAD

**Issue by CGsama** [mei23/misskey-v11#856]
## 💡 Summary

after change the setting to true, still can't follow or get notes from mastodon instance with secure mode

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

```
{
  "e": {
    "code": "StatusError",
    "message": "401 Unauthorized"
  },
  "ep": "ap/show",
  "ps": {
    "i": "xxxxxxxx",
    "uri": "https://xxxxxxxx/users/xxxxxxx"
  }
}

{
  "e": {
    "code": "StatusError",
    "message": "401 Unauthorized"
  },
  "ep": "ap/show",
  "ps": {
    "i": "xxxxxxxx",
    "uri": "https://xxxxxxxx/users/xxxxxx/statuses/xxxxxxxxx"
  }
}
```

**Comment by mei23** [comment]
It seems to work without any problems.
Please write the specific host and version.

Are you requesting from local? 
Certain versions of Mastodon have a bug that always causes an error when requesting from a host that cannot be reached remotely.

**Comment by CGsama** [comment]
Both from search and from remote server looks not working. I test on bgme.me, I cant get any update after they turn secure mode. And by using the renote option with redirection on mastodon, will get error "Internal error occurred. Please contact us if the error persists." on the small window.

**Comment by CGsama** [comment]
for server that with secure mode turn on after has conversation before, will remain connected. But if its a new server or the admin clear the key cache while turn on secure mode, it will not working. (my understanding, after take to their admin)

**Comment by CGsama** [comment]
I tried for a new startup misskey server, i can get the post and user without any problem. 
I spin up a mastodon server with secure mode and get this is the log on the mastodon side
by the way, one thing looks not usual is that i see three instance.actor account in my server after update
```
method=POST path=/interact/105646296654026891 format=html controller=RemoteInteractionController action=create status=302 duration=431.79 view=0.00 db=3.48 location=https://misskey.gothloli.club/authorize-follow
method=GET path=/users/admin/statuses/105646296654026891 format=json controller=StatusesController action=show status=401 duration=1252.85 view=1.62 db=5.06 key=https://misskey.gothloli.club/users/8hlff8aoks#main-key
```

**Comment by CGsama** [comment]
Yah that's the reason, after remove three actor account and let it generate a new one, everything works fine! Maybe there are some mutex issues when on actor but request multiple remote server at same time, i see the three actor were create almost same time. It may not a big deal. I left it open, but guess you can close the issue for now.

**Comment by mei23** [comment]
I will fix the mutex problem. 
Thank you.
